import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Crown, TrendingUp, Calendar, CreditCard, Settings, AlertCircle, CheckCircle, LogIn } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import SubscriptionPlans from '@/components/SubscriptionPlans';
import { StripeWrapper } from '@/components/StripeWrapper';
import { SubscriptionLogin } from '@/components/SubscriptionLogin';
import { getStoredDeviceFingerprint } from '@/utils/deviceFingerprint';

interface SubscriptionData {
  subscription?: {
    id: string;
    stripeSubscriptionId: string;
    status: string;
    currentPeriodEnd: Date;
  };
  tier: {
    id: string;
    name: string;
    model: string;
    monthlyPrice: number;
    limits: {
      documentsPerMonth: number;
      prioritySupport: boolean;
      advancedAnalysis: boolean;
      apiAccess: boolean;
    };
  };
  usage: {
    documentsAnalyzed: number;
    tokensUsed: number;
    cost: number;
    resetDate: Date;
  };
  canUpgrade: boolean;
  suggestedUpgrade?: {
    id: string;
    name: string;
    monthlyPrice: number;
  };
}

export default function SubscriptionPage() {
  const [subscriptionData, setSubscriptionData] = useState<SubscriptionData | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('overview');
  const [showLogin, setShowLogin] = useState(false);

  // Enable subscription functionality
  const [showComingSoon] = useState(false);

  useEffect(() => {
    // Check if this is a successful subscription return
    const urlParams = new URLSearchParams(window.location.search);
    const sessionId = urlParams.get('session_id');
    const success = urlParams.get('success');
    
    if (success === 'true' && sessionId) {
      // This is a successful subscription - we need to get the subscription token
      // The token will be generated by the webhook, but we can check for it
      handleSuccessfulSubscription(sessionId);
    } else {
      fetchSubscriptionData();
    }
  }, []);

  const handleSuccessfulSubscription = async (sessionId: string) => {
    try {
      // Wait a moment for webhook to process
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Try to get the subscription token
      try {
        const tokenResponse = await fetch(`/api/subscription/token/${sessionId}`);
        if (tokenResponse.ok) {
          const { token, subscription } = await tokenResponse.json();
          if (token) {
            localStorage.setItem('subscriptionToken', token);
            console.log('Stored subscription token from successful checkout');
            setSubscriptionData(subscription);
          }
        }
      } catch (tokenError) {
        console.log('No token available yet, fetching subscription data normally');
      }
      
      // Fallback to normal subscription fetch
      await fetchSubscriptionData();
      
      // Clear URL parameters
      window.history.replaceState({}, document.title, window.location.pathname);
    } catch (error) {
      console.error('Error handling successful subscription:', error);
      fetchSubscriptionData();
    }
  };

  const handleLoginSuccess = (token: string, subscription: any) => {
    setSubscriptionData(subscription);
    setShowLogin(false);
    setActiveTab('overview');
  };

  const fetchSubscriptionData = async () => {
    try {
      // Get subscription token from localStorage if available
      const subscriptionToken = localStorage.getItem('subscriptionToken');
      
      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };
      
      // Include subscription token and device fingerprint for security
      if (subscriptionToken) {
        headers['X-Subscription-Token'] = subscriptionToken;
        headers['X-Device-Fingerprint'] = getStoredDeviceFingerprint();
      }
      
      const response = await fetch('/api/user/subscription', {
        credentials: 'include',
        headers,
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();

      // Handle token validation results
      const returnedToken = response.headers.get('X-Subscription-Token');
      const tokenInvalid = response.headers.get('X-Subscription-Token-Invalid');
      
      if (tokenInvalid) {
        // Server indicates token is invalid - remove it
        localStorage.removeItem('subscriptionToken');
        console.log('Removed invalid subscription token');
      } else if (returnedToken) {
        localStorage.setItem('subscriptionToken', returnedToken);
        console.log('Confirmed subscription token is valid');
      }

      // Convert resetDate string back to Date object
      if (data.usage && data.usage.resetDate) {
        data.usage.resetDate = new Date(data.usage.resetDate);
      }

      setSubscriptionData(data);
    } catch (error) {
      console.error('Error fetching subscription data:', error);

      // Fallback to free tier data if API fails
      const fallbackData: SubscriptionData = {
        tier: {
          id: 'free',
          name: 'Free',
          model: 'gpt-3.5-turbo',
          monthlyPrice: 0,
          limits: {
            documentsPerMonth: -1,
            prioritySupport: false,
            advancedAnalysis: false,
            apiAccess: false,
          },
        },
        usage: {
          documentsAnalyzed: 0,
          tokensUsed: 0,
          cost: 0,
          resetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        },
        canUpgrade: true,
        suggestedUpgrade: {
          id: 'starter',
          name: 'Starter',
          monthlyPrice: 15,
        },
      };
      setSubscriptionData(fallbackData);
    } finally {
      setLoading(false);
    }
  };

  const handlePlanSelect = async (tierId: string, billingCycle: 'monthly' | 'yearly') => {
    if (tierId === 'free') {
      setActiveTab('overview');
      return;
    }

    try {
      // Create Stripe checkout session
      const response = await fetch('/api/subscription/create-checkout', {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          tierId,
          billingCycle,
        }),
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();

      if (data.error) {
        throw new Error(data.error);
      }

      // Redirect to Stripe checkout
      window.location.href = data.url;
    } catch (error) {
      console.error('Error creating checkout session:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      window.alert(`Failed to start checkout process: ${errorMessage}. Please try again or contact support.`);
    }
  };

  const handleCancelSubscription = async () => {
    if (window.confirm('Are you sure you want to cancel your subscription? You will be downgraded to the free plan at the end of your billing period.')) {
      try {
        const response = await fetch('/api/subscription/cancel', {
          method: 'POST',
          credentials: 'include',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            subscriptionId: subscriptionData?.subscription?.stripeSubscriptionId,
            immediate: false,
          }),
        });

        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }

        window.alert('Subscription canceled successfully. You will continue to have access until the end of your billing period.');
        fetchSubscriptionData(); // Refresh data
      } catch (error) {
        console.error('Error canceling subscription:', error);
        window.alert('Failed to cancel subscription. Please try again.');
      }
    }
  };

  // Show coming soon modal in production
  if (showComingSoon) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-slate-900 flex items-center justify-center">
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-8 max-w-md w-full mx-4">
            <div className="text-center">
              <Crown className="w-16 h-16 text-yellow-500 mx-auto mb-4" />
              <h2 className="text-2xl font-semibold mb-4 dark:text-white">Coming Soon</h2>
              <p className="text-gray-600 dark:text-gray-400 mb-6">
                Subscription management is coming soon! We're working hard to bring you premium features.
              </p>
              <Button 
                onClick={() => window.location.href = '/'}
                className="w-full"
              >
                Back to Home
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-slate-900 flex items-center justify-center">
        <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (!subscriptionData) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-slate-900 flex items-center justify-center">
        <Alert variant="destructive" className="max-w-md">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            Failed to load subscription data. Please try again.
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  const usagePercentage = subscriptionData.tier.limits.documentsPerMonth === -1
    ? 0 // Unlimited, so no percentage
    : (subscriptionData.usage.documentsAnalyzed / subscriptionData.tier.limits.documentsPerMonth) * 100;

  // Ensure resetDate is a Date object and is valid
  let resetDate: Date;
  try {
    resetDate = subscriptionData.usage.resetDate instanceof Date 
      ? subscriptionData.usage.resetDate 
      : new Date(subscriptionData.usage.resetDate);

    // Check if date is valid
    if (isNaN(resetDate.getTime())) {
      resetDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days from now as fallback
    }
  } catch (error) {
    resetDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days from now as fallback
  }

  const daysUntilReset = Math.max(0, Math.ceil((resetDate.getTime() - Date.now()) / (1000 * 60 * 60 * 24)));

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-900">
      <div className="max-w-7xl mx-auto px-4 py-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Subscription Management</h1>
              <p className="text-gray-600 dark:text-gray-300">Manage your subscription, view usage, and upgrade your plan</p>
            </div>
            
            {/* Always visible login button */}
            {subscriptionData.tier.id === 'free' && (
              <Button 
                variant="outline" 
                onClick={() => setShowLogin(true)}
                className="flex items-center space-x-2 whitespace-nowrap"
              >
                <LogIn className="h-4 w-4" />
                <span>Already Subscribed?</span>
              </Button>
            )}
          </div>
        </motion.div>

        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
          <TabsList className="grid w-full grid-cols-3 h-auto">
            <TabsTrigger value="overview" className="text-sm px-2 py-3 min-h-[44px] flex items-center justify-center">Overview</TabsTrigger>
            <TabsTrigger value="plans" className="text-sm px-2 py-3 min-h-[44px] flex items-center justify-center">Plans</TabsTrigger>
            <TabsTrigger value="billing" className="text-sm px-2 py-3 min-h-[44px] flex items-center justify-center">Billing</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            {/* Current Plan */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.1 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center space-x-2">
                    <Crown className="h-5 w-5 text-yellow-500" />
                    <span>Current Plan</span>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="text-xl font-semibold dark:text-white">{subscriptionData.tier.name}</h3>
                      <p className="text-gray-600 dark:text-gray-300">Powered by {subscriptionData.tier.model}</p>
                    </div>
                    <div className="text-right">
                      <div className="text-2xl font-bold dark:text-white">
                        {subscriptionData.tier.monthlyPrice === 0 ? 'Free' : `$${subscriptionData.tier.monthlyPrice}/month`}
                      </div>
                      {subscriptionData.tier.id !== 'free' && (
                        <Badge variant="secondary">Active</Badge>
                      )}
                    </div>
                  </div>

                                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                      <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                        <div className="text-xl font-semibold">
                          {subscriptionData.tier.limits.documentsPerMonth === -1 ? '∞' : subscriptionData.tier.limits.documentsPerMonth}
                        </div>
                        <div className="text-sm text-gray-600 dark:text-gray-300">Documents/Month</div>
                      </div>
                    <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                      <div className="text-xl font-semibold">
                        {subscriptionData.tier.limits.prioritySupport ? <CheckCircle className="h-6 w-6 text-green-500 mx-auto" /> : <span className="text-gray-400">-</span>}
                      </div>
                      <div className="text-sm text-gray-600 dark:text-gray-300">Priority Support</div>
                    </div>
                    <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                      <div className="text-xl font-semibold">
                        {subscriptionData.tier.limits.advancedAnalysis ? <CheckCircle className="h-6 w-6 text-green-500 mx-auto" /> : <span className="text-gray-400">-</span>}
                      </div>
                      <div className="text-sm text-gray-600 dark:text-gray-300">Advanced Analysis</div>
                    </div>
                    <div className="text-center p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                      <div className="text-xl font-semibold">
                        {subscriptionData.tier.limits.apiAccess ? <CheckCircle className="h-6 w-6 text-green-500 mx-auto" /> : <span className="text-gray-400">-</span>}
                      </div>
                      <div className="text-sm text-gray-600 dark:text-gray-300">API Access</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>

            {/* Usage Statistics - HIDDEN FOR DEVELOPMENT */}
            {/* 
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center space-x-2">
                    <TrendingUp className="h-5 w-5 text-blue-500" />
                    <span>Usage This Month</span>
                  </CardTitle>
                  <CardDescription>
                    Resets in {daysUntilReset} days ({resetDate.toLocaleDateString()})
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="dark:text-white">Documents Analyzed</span>
                      <span className="font-semibold dark:text-white">
                        {subscriptionData.usage.documentsAnalyzed} / {subscriptionData.tier.limits.documentsPerMonth === -1 ? '∞' : subscriptionData.tier.limits.documentsPerMonth}
                      </span>
                    </div>
                    {subscriptionData.tier.limits.documentsPerMonth === -1 ? (
                      <div className="h-2 bg-green-100 rounded-full flex items-center justify-center">
                        <span className="text-xs text-green-700 font-medium">Unlimited</span>
                      </div>
                    ) : (
                      <>
                        <Progress value={usagePercentage} className="h-2" />
                        {usagePercentage > 80 && (
                          <p className="text-sm text-orange-600 mt-1">
                            You're approaching your monthly limit
                          </p>
                        )}
                      </>
                    )}
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="text-center p-3 bg-blue-50 dark:bg-blue-900/30 rounded-lg">
                      <div className="text-xl font-semibold text-blue-600">
                        {subscriptionData.usage.tokensUsed.toLocaleString()}
                      </div>
                      <div className="text-sm text-gray-600 dark:text-gray-300">Tokens Used</div>
                    </div>
                    <div className="text-center p-3 bg-green-50 dark:bg-green-900/30 rounded-lg">
                      <div className="text-xl font-semibold text-green-600">
                        ${subscriptionData.usage.cost.toFixed(4)}
                      </div>
                      <div className="text-sm text-gray-600 dark:text-gray-300">AI Costs</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
            */}

            {/* Upgrade Suggestion or Login Option */}
            {subscriptionData.canUpgrade && subscriptionData.suggestedUpgrade && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
              >
                <Alert className="bg-blue-50 dark:bg-blue-900/30 border-blue-200 dark:border-blue-800">
                  <TrendingUp className="h-4 w-4" />
                  <AlertDescription>
                    <div className="flex items-center justify-between">
                      <div>
                        <strong className="dark:text-white">Ready to upgrade or already subscribed?</strong>
                        <p className="text-sm mt-1 dark:text-gray-300">
                          Upgrade to {subscriptionData.suggestedUpgrade.name} for just ${subscriptionData.suggestedUpgrade.monthlyPrice}/month, or log in if you already have a subscription.
                        </p>
                      </div>
                      <div className="flex space-x-2">
                        <Button 
                          variant="outline" 
                          onClick={() => setShowLogin(true)}
                          className="whitespace-nowrap"
                        >
                          Already Subscribed?
                        </Button>
                        <Button onClick={() => setActiveTab('plans')}>
                          View Plans
                        </Button>
                      </div>
                    </div>
                  </AlertDescription>
                </Alert>
              </motion.div>
            )}
          </TabsContent>

          <TabsContent value="plans">
            {/* Login option for existing subscribers */}
            {subscriptionData.tier.id === 'free' && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-6"
              >
                <Alert className="bg-green-50 dark:bg-green-900/30 border-green-200 dark:border-green-800">
                  <LogIn className="h-4 w-4" />
                  <AlertDescription>
                    <div className="flex items-center justify-between">
                      <div>
                        <strong className="dark:text-white">Already have a subscription?</strong>
                        <p className="text-sm mt-1 dark:text-gray-300">
                          If you've already subscribed, click here to access your account from this device.
                        </p>
                      </div>
                      <Button 
                        variant="outline" 
                        onClick={() => setShowLogin(true)}
                        className="whitespace-nowrap"
                      >
                        Access My Subscription
                      </Button>
                    </div>
                  </AlertDescription>
                </Alert>
              </motion.div>
            )}
            
            <StripeWrapper>
              <SubscriptionPlans
                currentTier={subscriptionData.tier.id}
                onSelectPlan={handlePlanSelect}
              />
            </StripeWrapper>
          </TabsContent>

          <TabsContent value="billing" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <CreditCard className="h-5 w-5 text-green-500" />
                  <span>Billing Information</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                {subscriptionData.tier.id === 'free' ? (
                  <div className="text-center py-8">
                    <Calendar className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                    <h3 className="text-lg font-semibold text-gray-600 dark:text-gray-300 mb-2">No Billing Information</h3>
                    <p className="text-gray-500 dark:text-gray-400 mb-4">You're currently on the free plan</p>
                    <Button onClick={() => setActiveTab('plans')}>
                      Upgrade to Paid Plan
                    </Button>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="flex justify-between items-center p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
                      <div>
                        <h4 className="font-semibold dark:text-white">Next Billing Date</h4>
                        <p className="text-gray-600 dark:text-gray-300">{subscriptionData.usage.resetDate.toLocaleDateString()}</p>
                      </div>
                      <div className="text-right">
                        <div className="text-xl font-bold dark:text-white">${subscriptionData.tier.monthlyPrice}</div>
                        <div className="text-sm text-gray-600 dark:text-gray-300">Monthly</div>
                      </div>
                    </div>

                    <div className="flex space-x-3">
                      <Button variant="outline" className="flex-1">
                        <Settings className="h-4 w-4 mr-2" />
                        Update Payment Method
                      </Button>
                      <Button
                        variant="destructive"
                        className="flex-1"
                        onClick={handleCancelSubscription}
                      >
                        Cancel Subscription
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>

      {/* Subscription Login Modal */}
      {showLogin && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-gray-800 rounded-lg max-w-md w-full">
            <SubscriptionLogin
              onSuccess={handleLoginSuccess}
              onCancel={() => setShowLogin(false)}
            />
          </div>
        </div>
      )}
    </div>
  );
}