import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Download, Share, Shield, ThumbsUp, AlertTriangle, XCircle, InfoIcon } from "lucide-react";
import type { Document, DocumentAnalysis } from "@shared/schema";

interface AnalysisResultsProps {
  document: Document;
}

export function AnalysisResults({ document }: AnalysisResultsProps) {
  const analysis = document.analysis as DocumentAnalysis;

  if (!analysis) {
    return (
      <Card className="p-8">
        <CardContent className="text-center">
          <p className="text-gray-600">No analysis available for this document.</p>
        </CardContent>
      </Card>
    );
  }

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'low':
        return 'bg-secondary/20 text-secondary';
      case 'moderate':
        return 'bg-warning/20 text-warning';
      case 'high':
        return 'bg-danger/20 text-danger';
      default:
        return 'bg-gray-200 text-gray-700';
    }
  };

  const getRiskIcon = (risk: string) => {
    switch (risk) {
      case 'low':
        return <Shield className="w-5 h-5 text-secondary" />;
      case 'moderate':
        return <AlertTriangle className="w-5 h-5 text-warning" />;
      case 'high':
        return <XCircle className="w-5 h-5 text-danger" />;
      default:
        return <InfoIcon className="w-5 h-5 text-gray-500" />;
    }
  };

  const handleExport = () => {
    try {
      // Create a simple text export of the analysis
      const exportContent = `
Document Analysis: ${document.title}

Overall Assessment: ${analysis.overallRisk.toUpperCase()} RISK

Summary:
${analysis.summary}

Key Findings:

Good Terms:
${analysis.keyFindings.goodTerms.map(term => `• ${term}`).join('\n')}

Review Needed:
${analysis.keyFindings.reviewNeeded.map(term => `• ${term}`).join('\n')}

Red Flags:
${analysis.keyFindings.redFlags.map(term => `• ${term}`).join('\n')}

Detailed Sections:
${analysis.sections.map(section => `
${section.title} (${section.riskLevel.toUpperCase()} RISK)
${section.summary}
${section.concerns ? section.concerns.map(concern => `• ${concern}`).join('\n') : ''}
`).join('\n')}

Generated by ReadMyFinePrint on ${new Date().toLocaleString()}
      `;

      // Check if we're in a browser environment
      if (typeof window !== 'undefined' && window.document) {
        const blob = new Blob([exportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = window.document.createElement('a');
        a.href = url;
        a.download = `${document.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-analysis.txt`;
        window.document.body.appendChild(a);
        a.click();
        window.document.body.removeChild(a);
        URL.revokeObjectURL(url);
      } else {
        // Fallback - copy to clipboard
        if (navigator.clipboard) {
          navigator.clipboard.writeText(exportContent);
        }
      }
    } catch (error) {
      console.error('Export failed:', error);
      // Fallback - copy to clipboard
      if (navigator.clipboard) {
        navigator.clipboard.writeText(`Document Analysis: ${document.title}\n\n${analysis.summary}`);
      }
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Analysis: ${document.title}`,
          text: analysis.summary,
          url: window.location.href,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(window.location.href);
    }
  };

  return (
    <Card className="p-8 mb-8">
      <CardContent className="p-0">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-2xl font-semibold text-text">Analysis Complete</h3>
            <p className="text-gray-600 mt-1">
              {document.title} - {document.content.split(' ').length} words analyzed
            </p>
          </div>
          <div className="flex items-center space-x-3">
            <Button
              onClick={handleExport}
              className="flex items-center space-x-2 bg-secondary text-white hover:bg-secondary/90"
            >
              <Download className="w-4 h-4" />
              <span>Export</span>
            </Button>
            <Button
              onClick={handleShare}
              variant="outline"
              className="flex items-center space-x-2"
            >
              <Share className="w-4 h-4" />
              <span>Share</span>
            </Button>
          </div>
        </div>

        {/* Overall Assessment */}
        <div className="bg-gradient-to-r from-secondary/10 to-primary/10 rounded-lg p-6 mb-8">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-secondary rounded-full flex items-center justify-center">
              {getRiskIcon(analysis.overallRisk)}
            </div>
            <div>
              <h4 className="text-lg font-semibold text-text">Overall Assessment</h4>
              <p className="text-sm text-gray-600">
                Risk Level:{" "}
                <span className={`font-medium ${
                  analysis.overallRisk === 'low' ? 'text-secondary' :
                  analysis.overallRisk === 'moderate' ? 'text-warning' : 'text-danger'
                }`}>
                  {analysis.overallRisk.charAt(0).toUpperCase() + analysis.overallRisk.slice(1)}
                </span>
              </p>
            </div>
          </div>
          <p className="text-gray-700">{analysis.summary}</p>
        </div>

        {/* Key Findings Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-secondary/5 border border-secondary/20 rounded-lg p-6">
            <div className="flex items-center space-x-3 mb-3">
              <ThumbsUp className="text-secondary text-lg" />
              <h4 className="font-semibold text-text">Good Terms</h4>
            </div>
            <ul className="space-y-2 text-sm text-gray-700">
              {analysis.keyFindings.goodTerms.map((term, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <span className="w-1.5 h-1.5 bg-secondary rounded-full mt-2 flex-shrink-0"></span>
                  <span>{term}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-warning/5 border border-warning/20 rounded-lg p-6">
            <div className="flex items-center space-x-3 mb-3">
              <AlertTriangle className="text-warning text-lg" />
              <h4 className="font-semibold text-text">Review Needed</h4>
            </div>
            <ul className="space-y-2 text-sm text-gray-700">
              {analysis.keyFindings.reviewNeeded.map((term, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <span className="w-1.5 h-1.5 bg-warning rounded-full mt-2 flex-shrink-0"></span>
                  <span>{term}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-danger/5 border border-danger/20 rounded-lg p-6">
            <div className="flex items-center space-x-3 mb-3">
              <XCircle className="text-danger text-lg" />
              <h4 className="font-semibold text-text">Red Flags</h4>
            </div>
            <ul className="space-y-2 text-sm text-gray-700">
              {analysis.keyFindings.redFlags.map((term, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <span className="w-1.5 h-1.5 bg-danger rounded-full mt-2 flex-shrink-0"></span>
                  <span>{term}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Detailed Breakdown */}
        <div className="space-y-6">
          <h4 className="text-xl font-semibold text-text border-b border-gray-200 pb-3">
            Detailed Breakdown
          </h4>

          {analysis.sections.map((section, index) => (
            <div key={index} className="border border-gray-200 rounded-lg overflow-hidden">
              <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
                <div className="flex items-center justify-between">
                  <h5 className="font-semibold text-text">{section.title}</h5>
                  <Badge className={getRiskColor(section.riskLevel)}>
                    {section.riskLevel.charAt(0).toUpperCase() + section.riskLevel.slice(1)}
                  </Badge>
                </div>
              </div>
              <div className="p-6">
                <div className="mb-4">
                  <h6 className="font-medium text-text mb-2 text-sm">Plain English Summary:</h6>
                  <p className="text-gray-700 text-sm leading-relaxed">{section.summary}</p>
                </div>
                {section.concerns && section.concerns.length > 0 && (
                  <div className={`border-l-4 p-4 rounded-r ${
                    section.riskLevel === 'high' ? 'bg-danger/5 border-danger' :
                    section.riskLevel === 'moderate' ? 'bg-warning/5 border-warning' :
                    'bg-secondary/5 border-secondary'
                  }`}>
                    <div className="flex items-start space-x-3">
                      {getRiskIcon(section.riskLevel)}
                      <div>
                        <p className={`font-medium text-sm mb-1 ${
                          section.riskLevel === 'high' ? 'text-danger' :
                          section.riskLevel === 'moderate' ? 'text-warning' :
                          'text-secondary'
                        }`}>
                          {section.riskLevel === 'high' ? 'Important Concern:' :
                           section.riskLevel === 'moderate' ? 'Important Note:' :
                           'Good to Know:'}
                        </p>
                        <ul className="text-gray-700 text-sm space-y-1">
                          {section.concerns.map((concern, concernIndex) => (
                            <li key={concernIndex}>• {concern}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
